backend:
  name: github
  repo: shreyabkatte/IndianCommunityToulouse
  branch: master

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "home"
    label: "Home Page"
    files:
      - file: "content/home.md"
        label: "Home Content"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Main Text", name: "body", widget: "markdown" }
